# Generated by Django 4.2.13 on 2024-06-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_pedido_lineapedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
