# Generated by Django 4.2.13 on 2024-07-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Línea Pedido', 'verbose_name_plural': 'Líneas Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
