# Generated by Django 4.2.13 on 2024-06-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sector', models.CharField(choices=[('vinadelmar', 'Viña del Mar'), ('valpo', 'Valparaíso'), ('quilpue', 'Quilpué'), ('concon', 'Concón')], max_length=50)),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
    ]
